### ISSUE TITLE
DnD supported for reordering?

### ISSUE THREAD

**Issue by zehawki** [hugobarragon/react-quizzes#3]
The demo here https://hugobarragon.github.io/react-quizzes/ shows a grab hand icon on the inserted form fields on hover... leading one to believe that the item can be dragged and dropped to reorder. Is that not supported?

**Comment by hugobarragon** [comment]
Hi, it is under development, but probabily will be on a next major version, because antd new version was released last year, that surpresses react lifecycles (componentDidmount)..
here is the reference to the project card, could you please add a print screen to your question?
https://github.com/hugobarragon/react-quizzes/projects/1#card-29331866

**Comment by hugobarragon** [comment]
@zehawki temporarly the questions can be ordered on the supplied array, but support will be added
